### ISSUE TITLE
Sensible error messages should be shown when listing a non-existing network

### ISSUE THREAD

**Issue by sanjay-saxena** [fabric-composer/fabric-composer#377]
If a developer tries to list a **non-existing**(i.e. before deploying) network, then the following is shown:

```
$ composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d
List business network digitalproperty-network
2017-03-07T19:22:24.818Z ERROR   FSConnectionProfileStore :load()                    Failed to loaded connection profile defaultProfile {"0":{"stack":["{Error}ENOENT: no such file or directory, open '/Users/sanjaysaxena/.composer-connection-profiles/defaultProfile/connection.json' Error: ENOENT: no such file or directory, open '/Users/sanjaysaxena/.composer-connection-profiles/defaultProfile/connection.json'","    at Error (native)"]}}$
Error: Failed to load connection profile defaultProfile
    at fs.readFile.then.catch (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/fsconnectionprofilestore.js:87:23)
Command completed successfully.

```
## Context
The error message should be more user-friendly.

## Expected Behavior
Ideally, the error message should inform the user that the specified network does not exist or has not been deployed.

## Actual Behavior
See above.

## Possible Fix
Show a useful error message.

## Steps to Reproduce
See above.

## Context
Just trying to learn HFC.

## Your Environment
* Version used: composer-cli  v0.4.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js v6.10.
* Operating System and version (desktop or mobile): Mac OS 10.12.1
* Link to your project:

**Comment by dselman** [comment]
Technically this means that the `defaultProfile` connection profile does not exist. The `defaultProfile` is created on first deploy.

**Comment by 14gracel** [comment]
```
Error: Failed to load connection profile defaultProfile
    at fs.readFile.then.catch (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/fsconnectionprofilestore.js:87:23)
``` 
part of the error to return 
```
Failed to load connection profile defaultProfile
```
and @mbwhite is investigating 
```
2017-03-07T19:22:24.818Z ERROR   FSConnectionProfileStore :load()                    Failed to loaded connection profile defaultProfile {"0":{"stack":["{Error}ENOENT: no such file or directory, open '/Users/sanjaysaxena/.composer-connection-profiles/defaultProfile/connection.json' Error: ENOENT: no such file or directory, open '/Users/sanjaysaxena/.composer-connection-profiles/defaultProfile/connection.json'","    at Error (native)"]}}$
```

**Comment by mbwhite** [comment]
Found the problem; some of the control values where set hardcoded;
