### ISSUE TITLE
Getting Started submit tx fails with 0.5.0 unstable

### ISSUE THREAD

**Issue by mbwhite** [fabric-composer/fabric-composer#424]
## Context
info: [Composer-GettingStarted] Fabric Composer: Getting Started appliation
info: [Composer-GettingStarted] LandRegistry:<init> businessNetworkDefinition obtained digitalproperty-network@0.0.1
info: [Composer-GettingStarted] updateForSale Getting assest from the registry.
error: [Composer-GettingStarted] LandRegsitry:updateForSale Error: Invalid or missing identifier for Type RegisterPropertyForSale in namespace net.biz.digitalPropertyNetwork
    at Factory.newResource (/home/matthew/github-demo/sample-applications/packages/getting-started/node_modules/composer-common/lib/factory.js:89:19)
    at Serializer.fromJSON (/home/matthew/github-demo/sample-applications/packages/getting-started/node_modules/composer-common/lib/serializer.js:141:37)
    at bizNetworkConnection.getAssetRegistry.then.then (/home/matthew/github-demo/sample-applications/packages/getting-started/lib/landRegistry.js:82:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
error: [Composer-GettingStarted] Error: Invalid or missing identifier for Type RegisterPropertyForSale in namespace net.biz.digitalPropertyNetwork
Command failed.
## Expected Behavior
Should run as per normal getting started.
## Steps to Reproduce

1. Run npm test in getting started
2.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mbwhite** [comment]
fabric-composer/sample-applications#12
