### ISSUE TITLE
yo generator for business network fails

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#668]
## Context
Cannot generate a skeleton business network.

## Expected Behavior
Should generate a template business network.

## Actual Behavior
```
? 'Allo Daniel! What would you like to do? Fabric Composer

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo fabric-composer

Welcome to the Fabric Composer Skeleton Application Generator
? Please select the type of Application: Skeleton Business Network
You can run this generator using: 'yo fabric-composer:businessnetwork'

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '../businessnetwork'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at constructor.configuring (/Users/dselman/.nvm/versions/node/v6.9.5/lib/node_modules/generator-fabric-composer/generators/app/index.js:74:38)
    at Object.<anonymous> (/Users/dselman/.nvm/versions/node/v6.9.5/lib/node_modules/generator-fabric-composer/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/dselman/.nvm/versions/node/v6.9.5/lib/node_modules/generator-fabric-composer/node_modules/run-async/index.js:25:25
    at /Users/dselman/.nvm/versions/node/v6.9.5/lib/node_modules/generator-fabric-composer/node_modules/run-async/index.js:24:19
    at /Users/dselman/.nvm/versions/node/v6.9.5/lib/node_modules/generator-fabric-composer/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```
## Steps to Reproduce

1. Run the generator
2. Select the skeleton business network option
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by 14gracel** [comment]
Fixed in PR #698
